create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text not null,
  referrer text,
  user_agent text,
  screen_width integer,
  screen_height integer,
  timezone text,
  visited_at timestamptz not null default now()
);

alter table public.visitor_events enable row level security;

drop policy if exists "Allow public visitor inserts" on public.visitor_events;

create policy "Allow public visitor inserts"
on public.visitor_events
for insert
to anon, authenticated
with check (true);
